# see https://www.elastic.co/guide/en/kibana/8.6/docker.html

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - "5601:5601"
    networks:
      - elastic


volumes:
  elastic-data: {}

networks:
  elastic: {}
